### ISSUE TITLE
Cannot deploy Openstack+LXD using localhost on 16.04 (AWS)

### ISSUE THREAD

**Issue by CalvinHartwell** [conjure-up/conjure-up#1418]
Hi all, 

I've tried several times to deploy Openstack on 16.04 using Conjure-up. This has worked back in November/December but doesn't seem to work anymore. I tried using the latest packages (apt install) and snaps, but neither work. 

I tried the steps in the following tutorials:
[https://www.youtube.com/watch?v=il3cGo8KG3I](https://www.youtube.com/watch?v=il3cGo8KG3I)
[https://insights.ubuntu.com/2018/02/02/tutorial-install-single-server-openstack-with-conjure-up](https://insights.ubuntu.com/2018/02/02/tutorial-install-single-server-openstack-with-conjure-up)
[https://www.ubuntu.com/download/cloud/try-openstack](https://www.ubuntu.com/download/cloud/try-openstack)

A video of my experience can be found here: [https://youtu.be/0JWTrFnEtXc](https://youtu.be/0JWTrFnEtXc). 

To summarize I tried two main installation methods: 

1) deploy VM on AWS using Azure with 64GB of Ram and 8 cores and 200GB disk.
2) SSH into the machine using Juju
3) Install packages for zfsutils-linux, lxd and conjure-up with apt. Run lxd init and configure the bridge and storage, next run conjure-up. this fails with this error: [https://askubuntu.com/questions/889860/conjure-up-openstack-error-error-flag-provided-but-not-defined-upload-tool/892543](https://askubuntu.com/questions/889860/conjure-up-openstack-error-error-flag-provided-but-not-defined-upload-tool/892543) ([https://youtu.be/0JWTrFnEtXc?t=377](https://youtu.be/0JWTrFnEtXc?t=377))

4) Destroy VM and re-run steps 1,2. However, step 3 uses snaps instead of apt packages. I also add the lxd group and add myself to it. 
5) The installation fails with the usual error that the bridge and networking are not configured ([https://youtu.be/0JWTrFnEtXc?t=1072](https://youtu.be/0JWTrFnEtXc?t=1072)) even though I've clearly just run the lxd init command. 

These steps should be corrected and updated on the Ubuntu website asap. 

Output of commands for juju info: 

```
ubuntu@ip-172-31-36-94:~$ which juju
/snap/bin/juju
ubuntu@ip-172-31-36-94:~$ juju version
2.3.7-xenial-amd64
ubuntu@ip-172-31-36-94:~$ which conjure-up
/snap/bin/conjure-up
ubuntu@ip-172-31-36-94:~$ conjure-up --version
which lxconjure-up 2.5.6
cubuntu@ip-172-31-36-94:~$ which lxc
/usr/bin/lxc
ubuntu@ip-172-31-36-94:~$ /snap/bin/lxc config show
config: {}
ubuntu@ip-172-31-36-94:~$ /snap/bin/lxc version
Client version: 3.0.0
Server version: 3.0.0
ubuntu@ip-172-31-36-94:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
```

Conjure-up cache backups: 

[https://drive.google.com/open?id=1oElvD7Z3FWjUuOrA1ew66eo8wZfr0gEg](https://drive.google.com/open?id=1oElvD7Z3FWjUuOrA1ew66eo8wZfr0gEgl)

## Sosreport

Please attach a sosreport:

```
#sudo apt install sosreport
#sosreport
# ??? missing additional packages for sosreport

ubuntu@ip-172-31-36-94:~$ sudo apt install sosreport
Reading package lists... Done
Building dependency tree       
Reading state information... Done
sosreport is already the newest version (3.5-1~ubuntu16.04.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
ubuntu@ip-172-31-36-94:~$ sosreport

sosreport (version 3.5)

no valid plugins were enabled
```

## What Spell was Selected?

Openstack with LXD 

## What provider (aws, maas, localhost, etc)?

localhost on AWS. 

### MAAS Users
N/A

## Commands ran

See video and tutorials for two different attempts using apt packages and  snaps. 

Please outline what commands were run to install and execute conjure-up:

sudo apt-get install conjure-up and snap install conjure-up were both tested. 

## Additional Information

Packaging of snap and apt versions should be consistent or it is misleading and leads to deployment issues.

**Comment by CalvinHartwell** [comment]
Why was this marked as won't fix?

**Comment by battlemidget** [comment]
I removed that wontfix label on Jul 5..

**Comment by carmine** [comment]
@battlemidget - Any commentary on why it was closed?

**Comment by battlemidget** [comment]
@carmine This should be fixed now

**Comment by KandiceLynne** [comment]
@battlemidget I am trying this now and this still throws the error "Unable to parse JSON output from LXD, does '/usr/bin/lxc query --wait -X GET /1.0' return info about the LXD server?" So this does not appear to be fixed.
