### ISSUE TITLE
Support passing a template to LXD

### ISSUE THREAD

**Issue by castrojo** [conjure-up/conjure-up#505]
We'd like to support deploying the canonical-kubernetes bundle on local providers for developers. Currently we need to use another template to get this to work, but Juju doesn't support this:

- https://bugs.launchpad.net/juju-core/+bug/1565872
- https://bugs.launchpad.net/juju/+bug/1552815

Idea: could we have conjure just handle the templates automatically so we can deploy kubes to LXD?

**Comment by battlemidget** [comment]
This will be addressed sooner than 2.1 just wanted to associate our next milestone with it

**Comment by battlemidget** [comment]
Still working on this, got mostly running except for now getting this error:

```
Nov 17 02:21:27 juju-74e418-9 kubelet[2361]: I1117 02:21:27.854138    2361 kubelet.go:2237] skipping pod synchronization - [Failed to start ContainerManager [open /proc/sys/kernel/panic: read-only file system, open /proc/sys/kernel/panic_on_oops: read-only file system, open /proc/sys/vm/overcommit_memory: read-only file system]]
```

You can try this out yourself with

```
conjure-up -d battlemidget/kubernetes-lxd
```

**Comment by battlemidget** [comment]
Now fixed with https://github.com/conjure-up/spells/pull/20

**Comment by sfarosu** [comment]
How did you resolve the "kubelet.go:1757] skipping pod synchronization - [Failed to start ContainerManager open /proc/sys/kernel/panic: read-only file system]"   issue?
I'm trying to install openshift origin in multiple lxd containers and i can't get pass this error in kubelet.

I should also mention:
Host machine: Ubuntu 16.04
Lxc containers use centos7 images
Lxd version: 2.19 using snap

My profile is:
config:
  boot.autostart: "false"
  linux.kernel_modules: openvswitch,nbd,ip_tables,ip6_tables,netlink_diag,nf_nat,overlay
  raw.lxc: |
    lxc.aa_profile=unconfined
    lxc.mount.auto=proc:mixed sys:rw
  security.nesting: "true"
  security.privileged: "true"
description: Default LXD profile
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/containers/bastion
- /1.0/containers/master1
- /1.0/containers/node1
- /1.0/containers/node2
- /1.0/containers/node3

**Comment by schu** [comment]
> How did you resolve the "kubelet.go:1757] skipping pod synchronization - [Failed to start ContainerManager open /proc/sys/kernel/panic: read-only file system]" issue?

In case this is still an issue: it should work with `... --config raw.lxc="lxc.mount.auto=proc:rw sys:rw" ...` (i.e. change `proc:mixed` to `proc:rw` to make sure `/proc/syc` is not mounted `ro` separately)

Hope that helps :)
